SELECT 

	SERVERPROPERTY('MACHINENAME') AS [MACHINE NAME]
	, ISNULL(SERVERPROPERTY('INSTANCENAME')
	, SERVERPROPERTY('MACHINENAME')) AS [INSTANCE NAME]
	, sl.NAME AS [LOGIN NAME]
	, CASE (PWDCOMPARE(sl.NAME,sl.PASSWORD_HASH))
			WHEN 1 THEN 'X'
			ELSE ''
	  END AS [PASSWORD SAME AS USER NAME]
	, CASE (PWDCOMPARE('',sl.PASSWORD_HASH))
			WHEN 1 THEN 'X'
			ELSE ''
	  END AS [PASSWORD IS NULL]
	  ,sp.create_date
FROM [master].[sys].[sql_logins] sl
INNER JOIN [master].[sys].[server_principals] sp ON sp.sid = sl.sid

WHERE

	PWDCOMPARE(sl.NAME,sl.PASSWORD_HASH) = 1 OR
	PWDCOMPARE('',sl.PASSWORD_HASH) = 1

ORDER BY sl.NAME
OPTION (MAXDOP 1)
