/*
ALTER DATABASE [SIRIUS1_DEV_1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [SIRIUS1_DEV_1]
FROM DISK = N'C:\MSSQL\Backup\SIRIUS1_DEV_1.bak'
WITH FILE = 1
   , NOUNLOAD
   , REPLACE
   , STATS = 1
ALTER DATABASE [SIRIUS1_DEV_1] SET MULTI_USER
GO
*/


USE [master]
GO

CREATE DATABASE [SIRIUS1_DEV_1] ON 
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data00.mdf' ),
( FILENAME = N'C:\MSSQL\Log\SIRIUS1_DEV_1_Log01.ldf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_brcIDpartition1.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_brcIDpartition2.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_BRCIDoverflow.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data03.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data04.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index03.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index04.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index05.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index06.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index07.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index08.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index09.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index10.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition4.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition5.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition6.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition7.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition8.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition9.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_ftrow_ContentAsHTML.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Index02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data05.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data06.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data07.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data08.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data09.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_Data10.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition1.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition2.mdf' ),
( FILENAME = N'C:\MSSQL\Data\SIRIUS1_DEV_1_docpartition3.mdf' )
 FOR ATTACH
GO


CREATE DATABASE [RegisterTakeOn1_DEV_1] ON 
( FILENAME = N'C:\MSSQL\Data\RegisterTakeOn1_DEV_1_Primary.mdf' ),
( FILENAME = N'C:\MSSQL\Log\RegisterTakeOn1_DEV_1_Log01.ldf' ),
( FILENAME = N'C:\MSSQL\Data\RegisterTakeOn1_DEV_1_Data01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RegisterTakeOn1_DEV_1_Data00.mdf' )
 FOR ATTACH
GO


CREATE DATABASE [AdventureWorks2019]
ON  (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019.mdf')
  , (FILENAME = N'C:\MSSQL\Log\AdventureWorks2019_log.ldf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_OLDER_THAN_202201.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202202.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202203.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202204.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202205.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202206.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202207.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202208.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202209.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202210.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202211.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202212.ndf')
  , (FILENAME = N'C:\MSSQL\Data\AdventureWorks2019_202301.ndf')
FOR ATTACH
GO


CREATE DATABASE [RTO1_DEV_1_Master] ON 
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Data00.mdf' ),
( FILENAME = N'C:\MSSQL\Log\RTO1_DEV_1_Master_Log01.ldf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Data01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Data02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Data03.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Index00.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Index01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Index02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Master_Index03.mdf' )
 FOR ATTACH
GO


CREATE DATABASE [RTO1_DEV_1_Template] ON 
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Data00.mdf' ),
( FILENAME = N'C:\MSSQL\Log\RTO1_DEV_1_Template_Log01.ldf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Data01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Data02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Data03.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Index00.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Index01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Index02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_Template_Index03.mdf' )
 FOR ATTACH
GO


/*

USE [master]
GO
CREATE DATABASE [RTO1_DEV_1_20147_2000000055] ON 
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055.mdf' ),
( FILENAME = N'C:\MSSQL\Log\RTO1_DEV_1_20147_2000000055_Log01.ldf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055_Data01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055_Data02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055_Data03.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055_Index00.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055_Index01.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055_Index02.mdf' ),
( FILENAME = N'C:\MSSQL\Data\RTO1_DEV_1_20147_2000000055_Index03.mdf' )
 FOR ATTACH
GO


USE [master]
ALTER DATABASE [AdventureWorks2019] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [AdventureWorks2019]
FROM DISK = N'C:\MSSQL\Backup\AdventureWorks2019.bak'
WITH FILE = 1
   , NOUNLOAD
   , REPLACE
   , STATS = 1
ALTER DATABASE [AdventureWorks2019] SET MULTI_USER
GO

ALTER DATABASE [SIRIUS1_DEV_1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [SIRIUS1_DEV_1]
FROM DISK = N'C:\MSSQL\Backup\SIRIUS1_DEV_1.bak'
WITH FILE = 1
   , NOUNLOAD
   , REPLACE
   , STATS = 1
ALTER DATABASE [SIRIUS1_DEV_1] SET MULTI_USER
GO

USE [master]
ALTER DATABASE [RegisterTakeOn1_DEV_1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [RegisterTakeOn1_DEV_1]
FROM DISK = N'C:\MSSQL\Backup\RegisterTakeOn1_DEV_1.bak'
WITH FILE = 1
   , MOVE N'Data00'
     TO N'C:\MSSQL\Data\RegisterTakeOn1_DEV_1_Data00.mdf'
   , MOVE N'Data01'
     TO N'C:\MSSQL\Data\RegisterTakeOn1_DEV_1_Data01.mdf'
   , MOVE N'Log01'
     TO N'C:\MSSQL\Log\RegisterTakeOn1_DEV_1_Log01.ldf'
   , NOUNLOAD
   , REPLACE
   , STATS = 1
ALTER DATABASE [RegisterTakeOn1_DEV_1] SET MULTI_USER
GO

*/


