USE [master]
GO

IF EXISTS (SELECT DB_ID('TestDB'))
BEGIN
    ALTER DATABASE [TestDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [TestDB]
END

CREATE DATABASE [TestDB]
ON PRIMARY (NAME = N'TestDB', FILENAME = N'C:\MSSQL\Data\TestDB.mdf')
LOG ON (NAME = N'TestDB_log', FILENAME = N'C:\MSSQL\Log\TestDB_log.ldf');
GO

USE [TestDB]
GO

DROP TABLE IF EXISTS [TestTable];
CREATE TABLE [TestTable]
(
    [a] CHAR(3000) NOT NULL DEFAULT (REPLICATE('a', 3000))
  , [b] CHAR(3000) NOT NULL DEFAULT (REPLICATE('b', 3000))
  , [c] CHAR(2000) NOT NULL DEFAULT (REPLICATE('c', 2000))
  , [d] CHAR(53)   NOT NULL DEFAULT (REPLICATE('d', 53))
); -- => 8053 + 7 bytes of internal overhead = 8060 bytes (max page data capacity)
GO

INSERT INTO [TestTable] DEFAULT VALUES;
GO 10